export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_SEARCHTEXT: 'SET_SEARCHTEXT',
	SET_POST_DATA: 'SET_POST_DATA',
	SET_POSTS_DATA: 'SET_POSTS_DATA',
	CLOSE_MODAL: 'CLOSE_MODAL',
	OPEN_MODAL: 'OPEN_MODAL',
	RESET_POST_DATA: 'RESET_POST_DATA',
	SET_USERS_DATA: 'SET_USERS_DATA',
};
